Test constructor
dh-center/st-retrospect-admin pull request #71
Opened 2020-11-09 13:17 UTC by Panda0412

2020-11-09 13:22 UTC, ilyamore88 requested changes

2020-11-09 13:22 UTC, ilyamore88 commented on src/editorjs-plugins/TestConstructor.tsx
> +  wrongAnswerMessage: string | undefined;
Нет доков

2020-11-09 13:22 UTC, ilyamore88 commented on src/editorjs-plugins/TestConstructor.tsx
> +  private currentWrongAnswerMessage: string | undefined;
Достаточно сделать поле `data: TestConstructorData`

2020-11-09 13:22 UTC, ilyamore88 commented on src/editorjs-plugins/TestConstructor.tsx
> +  answers: string[] | [] | undefined;
А зачем тут `[]`?

2020-11-09 13:33 UTC, ilyamore88 requested changes

2020-11-09 13:33 UTC, ilyamore88 commented on src/editorjs-plugins/TestConstructor.tsx
> +  public static get toolbox(): EditorJS.ToolboxConfig {
Достаточно использовать ToolboxConfig, он прекрасно импортируется без EditorJS. Тогда можно выпилить импорт EditorJS.

2020-11-12 19:44 UTC, ilyamore88 approved these changes

2020-11-12 20:22 UTC, nikmel2803 commented on src/editorjs-plugins/TestConstructor.tsx
> +      answers.push(blockContent.querySelectorAll('input')[i].value);
сделай только один раз querySelectorAll, присвой в переменную
это не самая быстрая операция

2020-11-12 23:00 UTC, nikmel2803 approved these changes

2020-11-12 23:01 UTC, merged